export const ActionTypes = {
  ADD_BLOG: "ADD_BLOG",
  EDIT_BLOG: "EDIT_BLOG",
  DELETE_BLOG: "DELETE_BLOG",
  LIKE_BLOG: "LIKE_BLOG",
  SELECTED_BLOG: "SELECTED_BLOG",
  REMOVE_SELECTED_BLOG: "REMOVE_SELECTED_BLOG",
};
